# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
name: Eleven Thirty
title: Design for Print and Screen
email: paul@eleventhirty.co
description: ""
keywords: ""
baseurl: ""
homeurl: "/"
twitter_username: eleventhirty
github_username:  pixelpaper
url: "http://eleventhirty.co"


# Build settings
markdown: kramdown
